### ISSUE TITLE
Refactor move status formatting function

### ISSUE THREAD

**Issue by tanjot** [shubhamchaudhary/pulla#14]
Shouldn't the  function which formats status in [pulla.py](pulla/pulla/pulla.py) be a part of [utils.py](pulla/pulla/utils.py).
```python
 def get_formatted_status_message(self, directory, status_msg):
        format_string = '{0:<' + str(self.max_dir_length + 10) + '} {1:<10}'
        return format_string.format(os.path.join(directory), status_msg)
````

**Comment by shubhamchaudhary** [comment]
I used the following lens to decide whether or not to move it out of Pulla:

* Who is printing the status message right now?
* Will it be used somewhere else? Consider that it needs max_dir_length, directory, and a status message.  Aren't these details making so specific to pulla that it can't be reused?

**Comment by shubhamchaudhary** [comment]
Is there something remaining in this story or can we close this?

**Comment by tanjot** [comment]
We can!!!
