### ISSUE TITLE
Use git flow for this repo

### ISSUE THREAD

**Issue by shubhamchaudhary** [shubhamchaudhary/pulla#15]
Checkout https://github.com/nvie/gitflow

These blogpost explain the flow:

* http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/
* http://nvie.com/posts/a-successful-git-branching-model/

**Comment by shubhamchaudhary** [comment]
Done from my side

**Comment by shubhamchaudhary** [comment]
Default branch for the repo has been set to 'develop' branch

**Comment by tanjot** [comment]
Another colorful and interesting link for [git-flow](http://danielkummer.github.io/git-flow-cheatsheet)

**Comment by tanjot** [comment]
Done!!!
