### ISSUE TITLE
Path separators on different platforms not handled

### ISSUE THREAD

**Issue by tanjot** [shubhamchaudhary/pulla#9]
When switching over different platforms, the hardcoded 'path separators' cause errors.

**Comment by shubhamchaudhary** [comment]
Specific places/lines of code or output would be great to add with this card

**Comment by tanjot** [comment]
As a sample for this issue, look into pulla/tests/test_utils.py: 
'class test_that_need_a_git_directory'

Function:
 @patch('os.path.isdir')
  def test_is_this_a_git_dir_returns_true_for_git_dir(self, mock_is_dir):
        test_dir= 'dummy_dir'
        possible_git_dir = test_dir + '\.git'
        mock_is_dir.return_value = True

Joining 'test_dir' and '.git' using a backslash('\') generates an error in windows wherein the file seperator used is('\'). We need to use a general procedure for joining any two paths instead of hardcoded path separators.
